### ISSUE TITLE
通过wait()和notify()去实现线程之间的通信，应该先执行wait()后执行notify()吧

### ISSUE THREAD

**Issue by WellKnight908** [wrayzheng/java-multithread-downloader#1]
主方法中的代码应该改一下

//等待 downloadMonitor 通知下载完成
try {
	synchronized(waiting) {
		waiting.wait();
	}
} catch (InterruptedException e) {
	System.err.println("Download interrupted.");
}
startDownloadMonitor();

**Comment by wrayzheng** [comment]
监视线程应该在主线程阻塞前启动，否则将出现死锁，主线程将永远阻塞。
逻辑上应该是某个线程等待使用资源，另一个线程才 notify 该线程，但这里由于是直接在主线程里 wait，所以必须在阻塞前启动监视线程，而且即使当前没有对象正在 wait，使用 notify 操作也不会造成影响。
